// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRmziKV3jEv_n-C0GtTlfEX-aBezHFpWc',
    appId: '1:533416174933:web:4dc02c4d8523c041fdfbdc',
    messagingSenderId: '533416174933',
    projectId: 'foodies-30144',
    authDomain: 'foodies-30144.firebaseapp.com',
    storageBucket: 'foodies-30144.firebasestorage.app',
    measurementId: 'G-J20NKLHLEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8XjLe-BVeQD4_DQgO-UtgSqXp19bh-98',
    appId: '1:533416174933:android:03d7aeceec9a8ef1fdfbdc',
    messagingSenderId: '533416174933',
    projectId: 'foodies-30144',
    storageBucket: 'foodies-30144.firebasestorage.app',
  );
}
